---
- name: Create network
  community.docker.docker_network:
    name: "{{ networkName }}"
    driver: overlay

- name: Deploy Services
  include: "../services/{{ item.name }}/service.yml"
  vars:
    - name: "{{ item.name }}"
    - version: "{{ item.version }}"
  loop: "{{ services }}"