---
- name: Deploy server
  hosts: deploy
  roles:
    - role: preconfig
      tags: preconfig
    - role: build
      tags: build  
    - role: deploy
      tags: deploy
    - role: initSwarm
      tags: initSwarm

- name: Manager server
  hosts: managers
  roles:
    - role: preconfig
      tags: preconfig
    - role: joinSwarm
      type: manager
      tags: joinSwarm

- name: Worker server
  hosts: workers
  roles:
    - role: preconfig 
      tags: preconfig
    - role: joinSwarm
      type: worker
      tags: joinSwarm