---
- name: Swarm initialization
  community.docker.docker_swarm:
    state: present
    advertise_addr: "{{ swarm_addr }}"
  register: token

- name: Tokens saving
  set_fact:
    token_manager: "{{ token.swarm_facts.JoinTokens.Manager }}"
    token_worker: "{{ token.swarm_facts.JoinTokens.Worker }}"
    cacheable: true