---
- name: Swarm initialization
  community.docker.docker_swarm:
    state: present
    advertise_addr: "{{ swarm_addr }}"
  register: token

- name: Directory create
  local_action:
    module: file
    path: ./tokens
    state: directory

- name: Managers token saving
  local_action:
    module: copy
    dest: ./tokens/token-manager
    content: "{{ token.swarm_facts.JoinTokens.Manager }}"

- name: Workers token saving
  local_action:
    module: copy
    dest: ./tokens/token-worker
    content: "{{ token.swarm_facts.JoinTokens.Worker }}"