---
- name: Swarm initialization
  community.docker.docker_swarm:
    state: present
    advertise_addr: "{{ swarm_addr }}"
  register: token

- name: Directory create
  file:
    path: ./tokens
    state: directory
    mode: '0644'
  delegate_to: localhost

- name: Managers token saving
  copy:
    dest: ./tokens/token-manager
    content: "{{ token.swarm_facts.JoinTokens.Manager }}"
    mode: '0644'
  delegate_to: localhost

- name: Workers token saving
  copy:
    dest: ./tokens/token-worker
    content: "{{ token.swarm_facts.JoinTokens.Worker }}"
    mode: '0644'
  delegate_to: localhost