---
- name: "Configuration config for [{{ name }}]"
  include: "../config.yml"
  loop:
    - nginx.conf
  loop_control:
    loop_var: "config_item"
- name: "Deploying Service [{{ name }}]"
  block:
    - name: "Deploy service [{{ name }}]"
      community.docker.docker_swarm_service:
        name: "{{ name }}"
        image: "nginx:{{ version }}"
        state: present
        force_update: true
        networks:
          - name: "{{ networkName }}"
        publish:
          - mode: ingress
            protocol: tcp
            published_port: 80
            target_port: 80
        configs:
          - config_name: nginx.conf
            filename: "/etc/nginx/nginx.conf"
  tags: "{{ name }}"