---
- name: "Configuration config for [{{ name }}]"
  block:
    - name: "Create config for [{{ name }}]"
      include: "config-create.yml"
  tags: "{{ name }}"
  
  rescue:
    - name: "Deleting service [{{ name }}]"
      community.docker.docker_swarm_service:
        name: "{{ name }}"
        state: absent

    - name: "Create config for [{{ name }}]"
      include: "config-create.yml"