---
- name: "Configuration secret for [{{ name }}]"
  block:
    - name: "Create secret for [{{ name }}]"
      include: "secret-create.yml"
  tags: "{{ name }}"
  
  rescue:
    - name: "Deleting service [{{ name }}]"
      community.docker.docker_swarm_service:
        name: "{{ name }}"
        state: absent

    - name: "Create secret for [{{ name }}]"
      include: "secret-create.yml"