---
- name: Installing Docker
  block:
    - name: Append Universe
      apt_repository:
        repo: deb http://ru.archive.ubuntu.com/ubuntu {{ ansible_distribution_release }} universe
        state: present
    - name: Installing additional packages
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg
          - lsb-release
          - python3-pip
        state: present
        cache_valid_time: 86400
    - name: Append docker keys
      apt_key:
        url: "https://download.docker.com/linux/ubuntu/gpg"
        state: present
        keyring: /usr/share/keyrings/docker-archive-keyring.gpg
    - name: Installing stable repository
      apt_repository:
        repo: >
          deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg]
          https://download.docker.com/linux/ubuntu
          {{ ansible_distribution_release }} stable
        update_cache: true
        filename: Docker
    - name: Installing docker-ce
      apt:
        name: docker-ce
        state: present
        update_cache: true
    - name: Restart docker
      service:
        name: docker
        state: restarted
        enabled: true
  become: true

- name: Installing docker-compose
  block:
    - name: Receving docker-composes last version
      uri:
        url: "https://api.github.com/repos/docker/compose/releases/latest"
        body_format: json
      register: page
    - name: Installing docker-compose
      get_url:
        url: "https://github.com/docker/compose/releases/download/{{ page.json.tag_name }}/docker-compose-Linux-x86_64"
        dest: /usr/local/bin/docker-compose
        mode: 0755
  become: true

- name: Installing additional packages for Python and Finishing Installation
  block:
    - name: Installing pip
      pip:
        name: docker
    - name: Ading user to group docker
      user:
        name: "{{ ansible_user }}"
        group: docker
        append: true
    - name: Reboot server machine
      reboot:
  become: true